version: '3'
services:
  gateway:
    build: ./gateway
    ports:
      - 3000:3001
    networks:
      - backend
  calculator:
    build: ./calc
    networks:
      - backend
  cache:
    build: ./cache
    networks:
      - backend

networks:
  backend:
    name: backend
